[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { version = "0.15.16", features = ["json", "toml"] }
egui = "0.32.3"
oxigen = "2.2.2"
polars = "0.51.0"
rayon = "1.11.0"
serde = { version = "1.0.226", features = ["derive"] }
